// Code generated for VlaDDoS service
// © VlaDDoS 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Vlad777-bit/personal-finance-analytics/ledger/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

type ReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportRepository) EXPECT() *ReportRepository_Expecter {
	return &ReportRepository_Expecter{mock: &_m.Mock}
}

// GetSummaryData provides a mock function with given fields: ctx, userID, from, to
func (_m *ReportRepository) GetSummaryData(ctx context.Context, userID string, from time.Time, to time.Time) ([]domain.CategoryReportData, error) {
	ret := _m.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaryData")
	}

	var r0 []domain.CategoryReportData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]domain.CategoryReportData, error)); ok {
		return rf(ctx, userID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []domain.CategoryReportData); ok {
		r0 = rf(ctx, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CategoryReportData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportRepository_GetSummaryData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummaryData'
type ReportRepository_GetSummaryData_Call struct {
	*mock.Call
}

// GetSummaryData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - from time.Time
//   - to time.Time
func (_e *ReportRepository_Expecter) GetSummaryData(ctx interface{}, userID interface{}, from interface{}, to interface{}) *ReportRepository_GetSummaryData_Call {
	return &ReportRepository_GetSummaryData_Call{Call: _e.mock.On("GetSummaryData", ctx, userID, from, to)}
}

func (_c *ReportRepository_GetSummaryData_Call) Run(run func(ctx context.Context, userID string, from time.Time, to time.Time)) *ReportRepository_GetSummaryData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *ReportRepository_GetSummaryData_Call) Return(_a0 []domain.CategoryReportData, _a1 error) *ReportRepository_GetSummaryData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportRepository_GetSummaryData_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]domain.CategoryReportData, error)) *ReportRepository_GetSummaryData_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
