// Code generated for VlaDDoS service
// © VlaDDoS 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	domain "github.com/Vlad777-bit/personal-finance-analytics/ledger/internal/domain"
	repository "github.com/Vlad777-bit/personal-finance-analytics/ledger/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, transaction
func (_m *TransactionRepository) Create(ctx context.Context, transaction domain.Transaction) (domain.Transaction, error) {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Transaction) (domain.Transaction, error)); ok {
		return rf(ctx, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Transaction) domain.Transaction); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction domain.Transaction
func (_e *TransactionRepository_Expecter) Create(ctx interface{}, transaction interface{}) *TransactionRepository_Create_Call {
	return &TransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, transaction)}
}

func (_c *TransactionRepository_Create_Call) Run(run func(ctx context.Context, transaction domain.Transaction)) *TransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Transaction))
	})
	return _c
}

func (_c *TransactionRepository_Create_Call) Return(_a0 domain.Transaction, _a1 error) *TransactionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Transaction) (domain.Transaction, error)) *TransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithinBudget provides a mock function with given fields: ctx, transaction
func (_m *TransactionRepository) CreateWithinBudget(ctx context.Context, transaction domain.Transaction) (domain.Transaction, error) {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithinBudget")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Transaction) (domain.Transaction, error)); ok {
		return rf(ctx, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Transaction) domain.Transaction); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_CreateWithinBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithinBudget'
type TransactionRepository_CreateWithinBudget_Call struct {
	*mock.Call
}

// CreateWithinBudget is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction domain.Transaction
func (_e *TransactionRepository_Expecter) CreateWithinBudget(ctx interface{}, transaction interface{}) *TransactionRepository_CreateWithinBudget_Call {
	return &TransactionRepository_CreateWithinBudget_Call{Call: _e.mock.On("CreateWithinBudget", ctx, transaction)}
}

func (_c *TransactionRepository_CreateWithinBudget_Call) Run(run func(ctx context.Context, transaction domain.Transaction)) *TransactionRepository_CreateWithinBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Transaction))
	})
	return _c
}

func (_c *TransactionRepository_CreateWithinBudget_Call) Return(_a0 domain.Transaction, _a1 error) *TransactionRepository_CreateWithinBudget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_CreateWithinBudget_Call) RunAndReturn(run func(context.Context, domain.Transaction) (domain.Transaction, error)) *TransactionRepository_CreateWithinBudget_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *TransactionRepository) List(ctx context.Context, filter repository.TransactionFilter) ([]domain.Transaction, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.TransactionFilter) ([]domain.Transaction, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.TransactionFilter) []domain.Transaction); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.TransactionFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TransactionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.TransactionFilter
func (_e *TransactionRepository_Expecter) List(ctx interface{}, filter interface{}) *TransactionRepository_List_Call {
	return &TransactionRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *TransactionRepository_List_Call) Run(run func(ctx context.Context, filter repository.TransactionFilter)) *TransactionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.TransactionFilter))
	})
	return _c
}

func (_c *TransactionRepository_List_Call) Return(_a0 []domain.Transaction, _a1 error) *TransactionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_List_Call) RunAndReturn(run func(context.Context, repository.TransactionFilter) ([]domain.Transaction, error)) *TransactionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SumByCategoryAndPeriod provides a mock function with given fields: ctx, userID, category, from, to
func (_m *TransactionRepository) SumByCategoryAndPeriod(ctx context.Context, userID string, category string, from time.Time, to time.Time) (int64, error) {
	ret := _m.Called(ctx, userID, category, from, to)

	if len(ret) == 0 {
		panic("no return value specified for SumByCategoryAndPeriod")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) (int64, error)); ok {
		return rf(ctx, userID, category, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) int64); ok {
		r0 = rf(ctx, userID, category, from, to)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, category, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_SumByCategoryAndPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumByCategoryAndPeriod'
type TransactionRepository_SumByCategoryAndPeriod_Call struct {
	*mock.Call
}

// SumByCategoryAndPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - category string
//   - from time.Time
//   - to time.Time
func (_e *TransactionRepository_Expecter) SumByCategoryAndPeriod(ctx interface{}, userID interface{}, category interface{}, from interface{}, to interface{}) *TransactionRepository_SumByCategoryAndPeriod_Call {
	return &TransactionRepository_SumByCategoryAndPeriod_Call{Call: _e.mock.On("SumByCategoryAndPeriod", ctx, userID, category, from, to)}
}

func (_c *TransactionRepository_SumByCategoryAndPeriod_Call) Run(run func(ctx context.Context, userID string, category string, from time.Time, to time.Time)) *TransactionRepository_SumByCategoryAndPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *TransactionRepository_SumByCategoryAndPeriod_Call) Return(_a0 int64, _a1 error) *TransactionRepository_SumByCategoryAndPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_SumByCategoryAndPeriod_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) (int64, error)) *TransactionRepository_SumByCategoryAndPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
