// Code generated for VlaDDoS service
// © VlaDDoS 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Vlad777-bit/personal-finance-analytics/ledger/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BudgetRepository is an autogenerated mock type for the BudgetRepository type
type BudgetRepository struct {
	mock.Mock
}

type BudgetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BudgetRepository) EXPECT() *BudgetRepository_Expecter {
	return &BudgetRepository_Expecter{mock: &_m.Mock}
}

// GetByCategory provides a mock function with given fields: ctx, userID, category
func (_m *BudgetRepository) GetByCategory(ctx context.Context, userID string, category string) (domain.Budget, error) {
	ret := _m.Called(ctx, userID, category)

	if len(ret) == 0 {
		panic("no return value specified for GetByCategory")
	}

	var r0 domain.Budget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.Budget, error)); ok {
		return rf(ctx, userID, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.Budget); ok {
		r0 = rf(ctx, userID, category)
	} else {
		r0 = ret.Get(0).(domain.Budget)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetRepository_GetByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCategory'
type BudgetRepository_GetByCategory_Call struct {
	*mock.Call
}

// GetByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - category string
func (_e *BudgetRepository_Expecter) GetByCategory(ctx interface{}, userID interface{}, category interface{}) *BudgetRepository_GetByCategory_Call {
	return &BudgetRepository_GetByCategory_Call{Call: _e.mock.On("GetByCategory", ctx, userID, category)}
}

func (_c *BudgetRepository_GetByCategory_Call) Run(run func(ctx context.Context, userID string, category string)) *BudgetRepository_GetByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *BudgetRepository_GetByCategory_Call) Return(_a0 domain.Budget, _a1 error) *BudgetRepository_GetByCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetRepository_GetByCategory_Call) RunAndReturn(run func(context.Context, string, string) (domain.Budget, error)) *BudgetRepository_GetByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *BudgetRepository) ListByUser(ctx context.Context, userID string) ([]domain.Budget, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []domain.Budget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Budget, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Budget); ok {
		r0 = rf(ctx, userID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.Budget)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type BudgetRepository_ListByUser_Call struct {
	*mock.Call
}

func (_e *BudgetRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *BudgetRepository_ListByUser_Call {
	return &BudgetRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *BudgetRepository_ListByUser_Call) Return(_a0 []domain.Budget, _a1 error) *BudgetRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Upsert provides a mock function with given fields: ctx, budget
func (_m *BudgetRepository) Upsert(ctx context.Context, budget domain.Budget) (domain.Budget, error) {
	ret := _m.Called(ctx, budget)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 domain.Budget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Budget) (domain.Budget, error)); ok {
		return rf(ctx, budget)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Budget) domain.Budget); ok {
		r0 = rf(ctx, budget)
	} else {
		r0 = ret.Get(0).(domain.Budget)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Budget) error); ok {
		r1 = rf(ctx, budget)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type BudgetRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - budget domain.Budget
func (_e *BudgetRepository_Expecter) Upsert(ctx interface{}, budget interface{}) *BudgetRepository_Upsert_Call {
	return &BudgetRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, budget)}
}

func (_c *BudgetRepository_Upsert_Call) Run(run func(ctx context.Context, budget domain.Budget)) *BudgetRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Budget))
	})
	return _c
}

func (_c *BudgetRepository_Upsert_Call) Return(_a0 domain.Budget, _a1 error) *BudgetRepository_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetRepository_Upsert_Call) RunAndReturn(run func(context.Context, domain.Budget) (domain.Budget, error)) *BudgetRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewBudgetRepository creates a new instance of BudgetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBudgetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BudgetRepository {
	mock := &BudgetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
