// Code generated for VlaDDoS service
// © VlaDDoS 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	domain "github.com/Vlad777-bit/personal-finance-analytics/ledger/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

type ReportRepository struct {
	mock.Mock
}

type ReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportRepository) EXPECT() *ReportRepository_Expecter {
	return &ReportRepository_Expecter{mock: &_m.Mock}
}

func (_m *ReportRepository) GetSummaryData(ctx context.Context, userID string, from time.Time, to time.Time) ([]domain.CategoryReportData, error) {
	ret := _m.Called(ctx, userID, from, to)
	if len(ret) == 0 {
		panic("no return value specified for GetSummaryData")
	}

	var r0 []domain.CategoryReportData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]domain.CategoryReportData, error)); ok {
		return rf(ctx, userID, from, to)
	}
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.CategoryReportData)
	}
	r1 = ret.Error(1)

	return r0, r1
}

type ReportRepository_GetSummaryData_Call struct {
	*mock.Call
}

func (_e *ReportRepository_Expecter) GetSummaryData(ctx interface{}, userID interface{}, from interface{}, to interface{}) *ReportRepository_GetSummaryData_Call {
	return &ReportRepository_GetSummaryData_Call{
		Call: _e.mock.On("GetSummaryData", ctx, userID, from, to),
	}
}

func (_c *ReportRepository_GetSummaryData_Call) Return(_a0 []domain.CategoryReportData, _a1 error) *ReportRepository_GetSummaryData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
