// Code generated for VlaDDoS service
// © VlaDDoS 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Vlad777-bit/personal-finance-analytics/ledger/internal/domain"
	service "github.com/Vlad777-bit/personal-finance-analytics/ledger/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// LedgerService is an autogenerated mock type for the LedgerService type
type LedgerService struct {
	mock.Mock
}

type LedgerService_Expecter struct {
	mock *mock.Mock
}

func (_m *LedgerService) EXPECT() *LedgerService_Expecter {
	return &LedgerService_Expecter{mock: &_m.Mock}
}

// CreateBudget provides a mock function with given fields: ctx, input
func (_m *LedgerService) CreateBudget(ctx context.Context, input service.CreateBudgetInput) (domain.Budget, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateBudget")
	}

	var r0 domain.Budget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateBudgetInput) (domain.Budget, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateBudgetInput) domain.Budget); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(domain.Budget)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.CreateBudgetInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LedgerService_CreateBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBudget'
type LedgerService_CreateBudget_Call struct {
	*mock.Call
}

// CreateBudget is a helper method to define mock.On call
//   - ctx context.Context
//   - input service.CreateBudgetInput
func (_e *LedgerService_Expecter) CreateBudget(ctx interface{}, input interface{}) *LedgerService_CreateBudget_Call {
	return &LedgerService_CreateBudget_Call{Call: _e.mock.On("CreateBudget", ctx, input)}
}

func (_c *LedgerService_CreateBudget_Call) Run(run func(ctx context.Context, input service.CreateBudgetInput)) *LedgerService_CreateBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.CreateBudgetInput))
	})
	return _c
}

func (_c *LedgerService_CreateBudget_Call) Return(_a0 domain.Budget, _a1 error) *LedgerService_CreateBudget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LedgerService_CreateBudget_Call) RunAndReturn(run func(context.Context, service.CreateBudgetInput) (domain.Budget, error)) *LedgerService_CreateBudget_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransaction provides a mock function with given fields: ctx, input
func (_m *LedgerService) CreateTransaction(ctx context.Context, input service.CreateTransactionInput) (domain.Transaction, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateTransactionInput) (domain.Transaction, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateTransactionInput) domain.Transaction); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.CreateTransactionInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LedgerService_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type LedgerService_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - input service.CreateTransactionInput
func (_e *LedgerService_Expecter) CreateTransaction(ctx interface{}, input interface{}) *LedgerService_CreateTransaction_Call {
	return &LedgerService_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, input)}
}

func (_c *LedgerService_CreateTransaction_Call) Run(run func(ctx context.Context, input service.CreateTransactionInput)) *LedgerService_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.CreateTransactionInput))
	})
	return _c
}

func (_c *LedgerService_CreateTransaction_Call) Return(_a0 domain.Transaction, _a1 error) *LedgerService_CreateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LedgerService_CreateTransaction_Call) RunAndReturn(run func(context.Context, service.CreateTransactionInput) (domain.Transaction, error)) *LedgerService_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactions provides a mock function with given fields: ctx, input
func (_m *LedgerService) GetTransactions(ctx context.Context, input service.GetTransactionsInput) ([]domain.Transaction, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.GetTransactionsInput) ([]domain.Transaction, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.GetTransactionsInput) []domain.Transaction); ok {
		r0 = rf(ctx, input)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.GetTransactionsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type LedgerService_GetTransactions_Call struct {
	*mock.Call
}

func (_e *LedgerService_Expecter) GetTransactions(ctx interface{}, input interface{}) *LedgerService_GetTransactions_Call {
	return &LedgerService_GetTransactions_Call{Call: _e.mock.On("GetTransactions", ctx, input)}
}

func (_c *LedgerService_GetTransactions_Call) Return(_a0 []domain.Transaction, _a1 error) *LedgerService_GetTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetBudgets provides a mock function with given fields: ctx, input
func (_m *LedgerService) GetBudgets(ctx context.Context, input service.GetBudgetsInput) ([]domain.Budget, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetBudgets")
	}

	var r0 []domain.Budget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.GetBudgetsInput) ([]domain.Budget, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.GetBudgetsInput) []domain.Budget); ok {
		r0 = rf(ctx, input)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.Budget)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.GetBudgetsInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type LedgerService_GetBudgets_Call struct {
	*mock.Call
}

func (_e *LedgerService_Expecter) GetBudgets(ctx interface{}, input interface{}) *LedgerService_GetBudgets_Call {
	return &LedgerService_GetBudgets_Call{Call: _e.mock.On("GetBudgets", ctx, input)}
}

func (_c *LedgerService_GetBudgets_Call) Return(_a0 []domain.Budget, _a1 error) *LedgerService_GetBudgets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetSummary provides a mock function with given fields: ctx, input
func (_m *LedgerService) GetSummary(ctx context.Context, input service.GetSummaryInput) (domain.Summary, error) {
	ret := _m.Called(ctx, input)
	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 domain.Summary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.GetSummaryInput) (domain.Summary, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.GetSummaryInput) domain.Summary); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(domain.Summary)
	}
	r1 = ret.Error(1)

	return r0, r1
}

type LedgerService_GetSummary_Call struct {
	*mock.Call
}

func (_e *LedgerService_Expecter) GetSummary(ctx interface{}, input interface{}) *LedgerService_GetSummary_Call {
	return &LedgerService_GetSummary_Call{Call: _e.mock.On("GetSummary", ctx, input)}
}

func (_c *LedgerService_GetSummary_Call) Return(_a0 domain.Summary, _a1 error) *LedgerService_GetSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// NewLedgerService creates a new instance of LedgerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLedgerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LedgerService {
	mock := &LedgerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
